/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kostease;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import util.Koneksi;
import util.Users;

/**
 *
 * @author mnish
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utama = new javax.swing.JPanel();
        tomboldaninput = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        utama.setPreferredSize(new java.awt.Dimension(1920, 1080));
        utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tomboldaninput.setOpaque(false);

        txtUsername.setBackground(new java.awt.Color(113, 82, 46));
        txtUsername.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtPassword.setBackground(new java.awt.Color(113, 82, 46));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(113, 82, 46));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel2.setText("Password");

        javax.swing.GroupLayout tomboldaninputLayout = new javax.swing.GroupLayout(tomboldaninput);
        tomboldaninput.setLayout(tomboldaninputLayout);
        tomboldaninputLayout.setHorizontalGroup(
            tomboldaninputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tomboldaninputLayout.createSequentialGroup()
                .addGroup(tomboldaninputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tomboldaninputLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(tomboldaninputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tomboldaninputLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        tomboldaninputLayout.setVerticalGroup(
            tomboldaninputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tomboldaninputLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        utama.add(tomboldaninput, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 670, 650, 340));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_login.png"))); // NOI18N
        background.setText("jLabel3");
        utama.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(utama, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1936, 1089));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginNow();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
//                new LoginPage().setVisible(true);
                Login LP = new Login();
                LP.setVisible(true);
                LP.setExtendedState(Frame.MAXIMIZED_BOTH); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel tomboldaninput;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPanel utama;
    // End of variables declaration//GEN-END:variables

    
    private void LoginNow() {
        String usr = txtUsername.getText();
        String pwd = new String(txtPassword.getPassword());
        try {
            Connection K = Koneksi.Go();
            Statement ST = K.createStatement();
            String Q = "SELECT * FROM user "
                    + "WHERE "
                    + "username='"+usr+"' AND "
                    + "password='"+pwd+"'";
            ResultSet RS = ST.executeQuery(Q);
            int n = 0;
            Users Us = new Users();
            while (RS.next()) {                
                n++;
                Us.setId(RS.getInt("id_user"));
                Us.setUsername(RS.getString("username"));
                Us.setNama(RS.getString("nama"));
                Us.setJabatan(RS.getString("jabatan"));
                Us.setEmail(RS.getString("email"));
                Us.setPassword(RS.getString("password"));
            }
            if(n>0){
                //System.out.println("Akun ditemukan");
                this.setVisible(false); 
                
                //
                DashboardAdmin DA = new DashboardAdmin();
                DA.Usr = Us;
                DA.setVisible(true);
                DA.setExtendedState(Frame.MAXIMIZED_BOTH); 
            }else {
                System.err.println("Akun tidak ditemukan");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi error:\n" + e.getMessage());
        }
        
        
    }


//    private void LoginNow() {
//        String usr = txtUsername.getText();
//        String pwd = new String(txtPassword.getPassword());
//        try {
//            Connection K = Koneksi.Go();
//            Statement ST = K.createStatement();
//            String Q = "SELECT * FROM pegawai "
//                    + "WHERE "
//                    + "username='"+usr+"' AND "
//                    + "password_hash='"+pwd+"'";
//            ResultSet RS = ST.executeQuery(Q);
//            int n = 0;
//            Pegawai Pg = new Pegawai();
//            while (RS.next()) {                
//                n++;
//                Pg.setId(RS.getInt("id_pegawai"));
//                Pg.setNama(RS.getString("nama_pegawai"));
//                Pg.setJabatan(RS.getString("nama_pegawai"));
//                Pg.setUsername(RS.getString("username"));
//                Pg.setPassword(RS.getString("password_hash"));
//            }
//            if(n>0){
//               
//                //System.out.println("Akun ditemukan");
//                this.setVisible(false); 
//                
//                //
//                DashboardAdmin DA = new DashboardAdmin();
//                DA.P = Pg;
//                DA.setVisible(true);
//                DA.setExtendedState(Frame.MAXIMIZED_BOTH); 
//            }else {
//                System.err.println("Akun tidak ditemukan");
//            }
//        } catch (Exception e) {
//        }
//        
//        
//    }
}
