/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dialogs;

import util.Pegawai;
import java.awt.BorderLayout;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JPanel;
import kostease.DashboardAdmin;
import kostease.Login;
//Eksperimen
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class Profil extends javax.swing.JDialog {

    private Pegawai P;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profil.class.getName());

    /**
     * Creates new form Profil
     */
    public Profil(java.awt.Frame parent, boolean modal, Pegawai user) {
        super(parent, modal);
        initComponents();
        this.P = user;
        setLocationRelativeTo(null);
    }

    public Profil(Object object, boolean b, Pegawai Usr) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private Profil(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utama = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtNama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        utama.setBackground(new java.awt.Color(213, 221, 51));
        utama.setPreferredSize(new java.awt.Dimension(360, 490));
        utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        utama.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 100, 30));

        txtNama.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNama.setText("Nama");
        txtNama.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtNamaComponentShown(evt);
            }
        });
        utama.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 200, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        utama.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email.png"))); // NOI18N
        utama.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 34, -1));

        txtEmail.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEmail.setText("Email");
        txtEmail.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtEmailComponentShown(evt);
            }
        });
        utama.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 270, -1));

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("N/A");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        utama.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 100, 100));

        txtUsername.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUsername.setText("Username");
        txtUsername.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtUsernameComponentShown(evt);
            }
        });
        utama.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 160, -1));

        getContentPane().add(utama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login P = new Login();
        this.setVisible(false);
        P.setVisible(true);
        P.setExtendedState(Frame.MAXIMIZED_BOTH);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNamaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtNamaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaComponentShown

    private void txtEmailComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtEmailComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadProfileImage();

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void txtUsernameComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtUsernameComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Profil dialog = new Profil(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtUsername;
    private javax.swing.JPanel utama;
    // End of variables declaration//GEN-END:variables

//Kode Eksperimen
    private void setInisial() {
        String username = P.getUsername();
        String inisial = "";

        if (username != null && username.length() >= 2) {
            inisial = username.substring(0, 2);
        } else if (username != null) {
            inisial = username.toUpperCase();
        } else {
            inisial = "N/A";
        }
        jLabel1.setText(inisial);
    }

    private void loadProfileImage() {
        txtUsername.setText(P.getUsername());
        txtNama.setText(P.getNama());
        txtEmail.setText(P.getEmail());
        if (P != null && P.getFotoProfil() != null) {
            try {
                URL url = new URL(P.getFotoProfil());
                BufferedImage img = ImageIO.read(url);

                ImageIcon icon = new ImageIcon(img);
                jLabel1.setText(null);
                jLabel1.setIcon(icon);

            } catch (IOException e) {
                System.err.println("Gagal memuat gambar dari URL (URL tidak valid atau kosong): " + e.getMessage());
                setInisial();
            }
        }
    }

}
