/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Locale;
import util.Koneksi;

/**
 *
 * @author ASUS
 */
public class BerandaOwner extends javax.swing.JPanel {

    /**
     * Creates new form BerandaOwner
     */
    public BerandaOwner() {
        initComponents();
        setFilterToCurrentDate();
        loadData();
    }

    private boolean isUpdating = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jumlahProdukTerjual = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tipeTerlaris = new javax.swing.JLabel();
        totalTerjualTipeKamar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        filterTahun = new javax.swing.JComboBox<>();
        filterTanggal = new javax.swing.JComboBox<>();
        filterBulan = new javax.swing.JComboBox<>();
        panelChart = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1610, 805));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 3, 36)); // NOI18N
        jLabel1.setText("INFO PENJUALAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 555, 91));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KAMAR TERJUAL SAAT INI");

        jumlahProdukTerjual.setFont(new java.awt.Font("Roboto", 1, 64)); // NOI18N
        jumlahProdukTerjual.setForeground(new java.awt.Color(255, 255, 255));
        jumlahProdukTerjual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahProdukTerjual.setText("87");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jumlahProdukTerjual, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jumlahProdukTerjual, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 670, 270));

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TIPE KAMAR TERLARIS SAAT INI");

        tipeTerlaris.setFont(new java.awt.Font("Roboto", 1, 64)); // NOI18N
        tipeTerlaris.setForeground(new java.awt.Color(255, 255, 255));
        tipeTerlaris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipeTerlaris.setText("STANDAR");

        totalTerjualTipeKamar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        totalTerjualTipeKamar.setForeground(new java.awt.Color(255, 255, 255));
        totalTerjualTipeKamar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalTerjualTipeKamar.setText("Total Terjual : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(tipeTerlaris, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(totalTerjualTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(tipeTerlaris, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(totalTerjualTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 650, 270));

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TOTAL PENDAPATAN SAAT INI");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 64)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Rp. 3.252.000,00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(418, 418, 418))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(517, 517, 517))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 1400, 270));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("TAHUN   :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 89, 35));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("BULAN   :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 96, 35));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("TANGGAL   :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 35));

        filterTahun.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        filterTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMUA", "2025", "2026" }));
        filterTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTahunActionPerformed(evt);
            }
        });
        jPanel1.add(filterTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 110, 40));

        filterTanggal.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        filterTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMUA", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        filterTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTanggalActionPerformed(evt);
            }
        });
        jPanel1.add(filterTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, 40));

        filterBulan.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        filterBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMUA", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        filterBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBulanActionPerformed(evt);
            }
        });
        jPanel1.add(filterBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 110, 40));

        panelChart.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panelChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 441, 1546, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void filterBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBulanActionPerformed
        if (!isUpdating) {
            updateTanggalCombo();
            loadData();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_filterBulanActionPerformed

    private void filterTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTanggalActionPerformed
        if (!isUpdating) {
            updateTanggalCombo();
            loadData();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_filterTanggalActionPerformed

    private void filterTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTahunActionPerformed

        updateTanggalCombo();
        loadData();

        // TODO add your handling code here:
    }//GEN-LAST:event_filterTahunActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> filterBulan;
    private javax.swing.JComboBox<String> filterTahun;
    private javax.swing.JComboBox<String> filterTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jumlahProdukTerjual;
    private javax.swing.JPanel panelChart;
    private javax.swing.JLabel tipeTerlaris;
    private javax.swing.JLabel totalTerjualTipeKamar;
    // End of variables declaration//GEN-END:variables

    private void setFilterToCurrentDate() {
        java.util.Calendar cal = java.util.Calendar.getInstance();
        int tgl = cal.get(java.util.Calendar.DAY_OF_MONTH);
        int bln = cal.get(java.util.Calendar.MONTH) + 1; 
        int thn = cal.get(java.util.Calendar.YEAR);

        updateTanggalCombo(); 

        filterTanggal.setSelectedItem(String.valueOf(tgl));
        filterBulan.setSelectedItem(String.valueOf(bln));
        filterTahun.setSelectedItem(String.valueOf(thn));
    }

    private void updateTanggalCombo() {
        isUpdating = true;
        String selectedBulan = filterBulan.getSelectedItem().toString();
        String selectedTahun = filterTahun.getSelectedItem().toString();
        Object currentTgl = filterTanggal.getSelectedItem();

       
        if (selectedBulan.equals("SEMUA") || selectedTahun.equals("SEMUA")) {
            return;
        }

        int bulan = Integer.parseInt(selectedBulan);
        int tahun = Integer.parseInt(selectedTahun);

        java.util.Calendar cal = new java.util.GregorianCalendar(tahun, bulan - 1, 1);
        int daysInMonth = cal.getActualMaximum(java.util.Calendar.DAY_OF_MONTH);

        filterTanggal.removeAllItems();
        filterTanggal.addItem("SEMUA");
        for (int i = 1; i <= daysInMonth; i++) {
            filterTanggal.addItem(String.valueOf(i));
        }

        if (currentTgl != null) {
            filterTanggal.setSelectedItem(currentTgl);
        }

        isUpdating = false; 
    }

    public void loadData() {
        if (filterTanggal.getSelectedItem() == null
                || filterBulan.getSelectedItem() == null
                || filterTahun.getSelectedItem() == null) {
            return; 
        }
        try {
            Connection conn = Koneksi.Colok();
            String tgl = filterTanggal.getSelectedItem().toString();
            String bln = filterBulan.getSelectedItem().toString();
            String thn = filterTahun.getSelectedItem().toString();

     
            String filterSQL = "";
            if (!tgl.equals("SEMUA")) {
                filterSQL += " AND DAY(p.tanggal) = " + tgl;
            }
            if (!bln.equals("SEMUA")) {
                filterSQL += " AND MONTH(p.tanggal) = " + bln;
            }
            if (!thn.equals("SEMUA")) {
                filterSQL += " AND YEAR(p.tanggal) = " + thn;
            }

         
            String sqlTerjual = "SELECT COUNT(dp.id_kamar) as total FROM detail_pembayaran dp "
                    + "JOIN pembayaran p ON dp.id_pembayaran = p.id_pembayaran WHERE 1=1" + filterSQL;

        
            String sqlTerlaris = "SELECT k.tipe_kamar, COUNT(dp.id_kamar) as qty FROM detail_pembayaran dp "
                    + "JOIN kamar k ON dp.id_kamar = k.id_kamar "
                    + "JOIN pembayaran p ON dp.id_pembayaran = p.id_pembayaran "
                    + "WHERE 1=1" + filterSQL
                    + " GROUP BY k.tipe_kamar ORDER BY qty DESC LIMIT 1";

            String sqlProfit = "SELECT SUM((dp.harga - k.hpp) * dp.jumlah_pembayaran) as profit FROM detail_pembayaran dp "
                    + "JOIN kamar k ON dp.id_kamar = k.id_kamar "
                    + "JOIN pembayaran p ON dp.id_pembayaran = p.id_pembayaran "
                    + "WHERE 1=1" + filterSQL.replace("p.tanggal", "p.tanggal");
  

            Statement st = conn.createStatement();

            ResultSet rs1 = st.executeQuery(sqlTerjual);
            jumlahProdukTerjual.setText(rs1.next() ? String.valueOf(rs1.getInt("total")) : "0");

            ResultSet rs2 = st.executeQuery(sqlTerlaris);
            if (rs2.next()) {
                tipeTerlaris.setText(rs2.getString("tipe_kamar"));
                totalTerjualTipeKamar.setText("Total Terjual: " + rs2.getInt("qty"));
            } else {
                tipeTerlaris.setText("-");
                totalTerjualTipeKamar.setText("Total Terjual: 0");
            }

            ResultSet rs3 = st.executeQuery(sqlProfit);
            double profit = rs3.next() ? rs3.getDouble("profit") : 0;
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
            jLabel5.setText(nf.format(profit));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
