/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import javax.swing.table.DefaultTableModel;
import util.Koneksi;

/**
 *
 * @author ASUS
 */
public class KinerjaKasir extends javax.swing.JPanel {

    /**
     * Creates new form KinerjaKasir
     */
    public KinerjaKasir() {
        initComponents();
        setFilterToCurrentDate();
        loadData();
    }

    private boolean isUpdating = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filterBulan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        filterTanggal = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        filterTahun = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1610, 805));

        jLabel1.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        jLabel1.setText("KIRNERJA KASIR");

        jTable1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Kasir", "Jumlah Transaksi", "Jumlah Pendapatan"
            }
        ));
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        filterBulan.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        filterBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMUA", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        filterBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBulanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("BULAN   :");

        filterTanggal.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        filterTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMUA", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        filterTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTanggalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("TANGGAL   :");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("TAHUN   :");

        filterTahun.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        filterTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMUA", "2025", "2026" }));
        filterTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTahunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(filterTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(filterBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(filterTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(851, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void filterBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBulanActionPerformed
        if (!isUpdating) {
            updateTanggalCombo();
            loadData();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_filterBulanActionPerformed

    private void filterTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTanggalActionPerformed
        if (!isUpdating) {
            updateTanggalCombo();
            loadData();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_filterTanggalActionPerformed

    private void filterTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTahunActionPerformed
        updateTanggalCombo();
        loadData();
        // TODO add your handling code here:
    }//GEN-LAST:event_filterTahunActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> filterBulan;
    private javax.swing.JComboBox<String> filterTahun;
    private javax.swing.JComboBox<String> filterTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void setFilterToCurrentDate() {
        java.util.Calendar cal = java.util.Calendar.getInstance();
        int tgl = cal.get(java.util.Calendar.DAY_OF_MONTH);
        int bln = cal.get(java.util.Calendar.MONTH) + 1; // Calendar dimulai dari 0
        int thn = cal.get(java.util.Calendar.YEAR);

        updateTanggalCombo(); // Pastikan jumlah hari benar dulu

        filterTanggal.setSelectedItem(String.valueOf(tgl));
        filterBulan.setSelectedItem(String.valueOf(bln));
        filterTahun.setSelectedItem(String.valueOf(thn));
    }

    private void updateTanggalCombo() {
        isUpdating = true;
        String selectedBulan = filterBulan.getSelectedItem().toString();
        String selectedTahun = filterTahun.getSelectedItem().toString();
        Object currentTgl = filterTanggal.getSelectedItem();

        // Jika pilih "SEMUA", kita tidak perlu mengubah jumlah hari (default 31)
        if (selectedBulan.equals("SEMUA") || selectedTahun.equals("SEMUA")) {
            return;
        }

        int bulan = Integer.parseInt(selectedBulan);
        int tahun = Integer.parseInt(selectedTahun);

        java.util.Calendar cal = new java.util.GregorianCalendar(tahun, bulan - 1, 1);
        int daysInMonth = cal.getActualMaximum(java.util.Calendar.DAY_OF_MONTH);

        filterTanggal.removeAllItems();
        filterTanggal.addItem("SEMUA");
        for (int i = 1; i <= daysInMonth; i++) {
            filterTanggal.addItem(String.valueOf(i));
        }

        if (currentTgl != null) {
            filterTanggal.setSelectedItem(currentTgl);
        }

        isUpdating = false; // Buka kunci

        // Kembalikan pilihan user sebelumnya jika masih tersedia
    }

    private void loadData() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Bersihkan tabel sebelum memuat data baru

    try {
        java.sql.Connection conn = Koneksi.Colok(); // Sesuaikan dengan nama class koneksi Anda
        
        // Ambil nilai dari filter
        String tgl = filterTanggal.getSelectedItem().toString();
        String bln = filterBulan.getSelectedItem().toString();
        String thn = filterTahun.getSelectedItem().toString();

        // Query dasar: Join pegawai (sebagai kasir) dengan pembayaran
        // Kita hitung COUNT untuk jumlah transaksi dan SUM untuk pendapatan
        String sql = "SELECT p.nama AS nama_kasir, "
                   + "COUNT(b.id_pembayaran) AS jumlah_transaksi, "
                   + "SUM(b.total_harga) AS total_pendapatan "
                   + "FROM pegawai p "
                   + "LEFT JOIN pembayaran b ON p.id_pegawai = b.id_pegawai "
                   + "WHERE p.jabatan = 'KASIR' ";

        // Tambahkan filter dinamis berdasarkan pilihan JComboBox
        if (!tgl.equals("SEMUA")) {
            sql += " AND DAY(b.tanggal) = " + tgl;
        }
        if (!bln.equals("SEMUA")) {
            sql += " AND MONTH(b.tanggal) = " + bln;
        }
        if (!thn.equals("SEMUA")) {
            sql += " AND YEAR(b.tanggal) = " + thn;
        }

        sql += " GROUP BY p.id_pegawai, p.nama";

        java.sql.Statement stmt = conn.createStatement();
        java.sql.ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {
            String namaKasir = rs.getString("nama_kasir");
            int jumlahTransaksi = rs.getInt("jumlah_transaksi");
            double pendapatan = rs.getDouble("total_pendapatan");

            model.addRow(new Object[]{
                namaKasir,
                jumlahTransaksi,
                "Rp " + String.format("%,.2f", pendapatan)
            });
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        e.printStackTrace();
    }
}
    
    
}
