/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import util.Koneksi;

/**
 *
 * @author ASUS
 */
public class LaporanKeuanganHarian extends javax.swing.JPanel {

    /**
     * Creates new form LaporanKeuanganHarian
     */
    private int currentIdPegawai;

    public LaporanKeuanganHarian(int idPegawai) {
        initComponents();
        this.currentIdPegawai = idPegawai;
        java.time.LocalDate hariIni = java.time.LocalDate.now();
        txtHari.setText(hariIni.toString());

        loadLaporanHariIni(idPegawai, hariIni.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHari = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelLaporan = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1610, 805));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1610, 805));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setPreferredSize(new java.awt.Dimension(1610, 100));

        jLabel1.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel1.setText("Laporan Keuangan Harian");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Tanggal   :");

        txtHari.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtHari.setText("...");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHari, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1356, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHari))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, -1));

        tabelLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Kamar", "No Kamar", "HPP", "Harga", "Jumlah", "Keuntungan"
            }
        ));
        tabelLaporan.setRowHeight(40);
        tabelLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelLaporanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelLaporan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1620, 640));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelLaporanMouseClicked

    }//GEN-LAST:event_tabelLaporanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tabelLaporan;
    private javax.swing.JLabel txtHari;
    // End of variables declaration//GEN-END:variables

    private void loadLaporanHariIni(int idPegawai, String tanggal) {
        DefaultTableModel model = (DefaultTableModel) tabelLaporan.getModel();
        model.setRowCount(0); // Membersihkan tabel sebelum isi data baru

        String sql = "SELECT k.id_kamar, k.no_kamar, k.hpp, dp.harga, dp.jumlah_pembayaran, "
                + "((dp.harga - k.hpp) * dp.jumlah_pembayaran) AS keuntungan "
                + "FROM detail_pembayaran dp "
                + "JOIN kamar k ON dp.id_kamar = k.id_kamar "
                + "JOIN pembayaran p ON dp.id_pembayaran = p.id_pembayaran "
                + "WHERE p.id_pegawai = ? AND DATE(p.tanggal) = ?";

        try (Connection conn = Koneksi.Go(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, idPegawai);
            ps.setString(2, tanggal);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_kamar"),
                    rs.getString("no_kamar"),
                    rs.getString("hpp"),
                    rs.getString("harga"),
                    rs.getInt("jumlah_pembayaran"),
                    rs.getString("keuntungan")
                });
            }
        } catch (SQLException e) {
            System.out.println("Gagal memuat laporan: " + e.getMessage());
        }
    }

}
