/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import dialogs.AddKamar;
import dialogs.DeleteDataKamar;
import dialogs.EditDataKamar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Koneksi;
import util.Kamar;

/**
 *
 * @author USER
 */
public class ManageKamar extends javax.swing.JPanel {

    Kamar Dk;

    /**
     * Creates new form MangeKamar
     */
    public ManageKamar() {
        initComponents();
        refreshDataKamar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utama = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        txtEdit = new javax.swing.JButton();
        txtAdd = new javax.swing.JButton();
        txtDelete = new javax.swing.JButton();
        txtRefresh = new javax.swing.JButton();
        contain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        utama.setBackground(new java.awt.Color(255, 255, 255));
        utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setPreferredSize(new java.awt.Dimension(1610, 100));

        jLabel1.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel1.setText("Manage Kamar");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearch.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtSearch.setText("Search...");
        txtSearch.setPreferredSize(new java.awt.Dimension(62, 21));
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, 30));

        txtEdit.setBackground(new java.awt.Color(0, 153, 255));
        txtEdit.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtEdit.setForeground(new java.awt.Color(255, 255, 255));
        txtEdit.setText("Edit");
        txtEdit.setEnabled(false);
        txtEdit.setPreferredSize(new java.awt.Dimension(72, 26));
        txtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditActionPerformed(evt);
            }
        });

        txtAdd.setBackground(new java.awt.Color(0, 255, 0));
        txtAdd.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtAdd.setForeground(new java.awt.Color(255, 255, 255));
        txtAdd.setText("ADD");
        txtAdd.setPreferredSize(new java.awt.Dimension(72, 26));
        txtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddActionPerformed(evt);
            }
        });

        txtDelete.setBackground(new java.awt.Color(255, 51, 51));
        txtDelete.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtDelete.setForeground(new java.awt.Color(255, 255, 255));
        txtDelete.setText("DELETE");
        txtDelete.setEnabled(false);
        txtDelete.setPreferredSize(new java.awt.Dimension(82, 26));
        txtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteActionPerformed(evt);
            }
        });

        txtRefresh.setBackground(new java.awt.Color(255, 204, 0));
        txtRefresh.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtRefresh.setForeground(new java.awt.Color(255, 255, 255));
        txtRefresh.setText("REFRESH");
        txtRefresh.setPreferredSize(new java.awt.Dimension(82, 26));
        txtRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 838, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        utama.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        contain.setBackground(new java.awt.Color(204, 0, 204));
        contain.setPreferredSize(new java.awt.Dimension(1610, 705));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_kamar", "no_kamar", "tipe_kamar", "hpp", "harga_harian", "deskripsi", "link_gambar", "id_status"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(1610, 670));
        jTable1.setRowHeight(40);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout containLayout = new javax.swing.GroupLayout(contain);
        contain.setLayout(containLayout);
        containLayout.setHorizontalGroup(
            containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1610, Short.MAX_VALUE)
        );
        containLayout.setVerticalGroup(
            containLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );

        utama.add(contain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        add(utama, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        AddKamar NK = new AddKamar(null, true);
        NK.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddActionPerformed

    private void txtRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRefreshActionPerformed
        txtEdit.setEnabled(false);
        txtDelete.setEnabled(false);
        jTable1.clearSelection();
        refreshDataKamar("");
        txtSearch.setText("Search...");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefreshActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int n = jTable1.getSelectedRow();
        if (n != -1) {
            txtEdit.setEnabled(true);
            txtDelete.setEnabled(true);
            Dk = new Kamar();
            String IDkmr = jTable1.getValueAt(n, 0).toString();
            int ID = Integer.valueOf(IDkmr);
            String no_kamar = jTable1.getValueAt(n, 1).toString();
            String tipe_kamar = jTable1.getValueAt(n, 2).toString();
            String hpp_kamar = jTable1.getValueAt(n,3).toString();
            String harga_harian = jTable1.getValueAt(n, 4).toString();
            String deskripsi = jTable1.getValueAt(n, 5).toString();
            String gambar = jTable1.getValueAt(n, 6).toString();
            String status = jTable1.getValueAt(n, 7).toString();
            int status_kmr = Integer.valueOf(status);
            Dk.setId(ID);
            Dk.setNoKamar(no_kamar);
            Dk.setTipe(tipe_kamar);
            Dk.setHpp(hpp_kamar);
            Dk.setHargaHarian(harga_harian);
            Dk.setDeskripsi(deskripsi);
            Dk.setGambar(gambar);
            Dk.setStatus(status_kmr);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            EditDataKamar ek = new EditDataKamar(null, true);
            ek.Edk = Dk;
            ek.setVisible(true);
        } else {
            //
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditActionPerformed

    private void txtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteActionPerformed
        DeleteDataKamar ddk = new DeleteDataKamar(null, true);
        ddk.Ddk = Dk;
        ddk.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        txtSearch.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        searchDataKamar();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contain;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTable1;
    private javax.swing.JButton txtAdd;
    private javax.swing.JButton txtDelete;
    private javax.swing.JButton txtEdit;
    private javax.swing.JButton txtRefresh;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JPanel utama;
    // End of variables declaration//GEN-END:variables

    public static void refreshDataKamar(String w) {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            Connection K = Koneksi.Go();
            String Q = "SELECT * FROM kamar" + w;
            Statement S = K.createStatement();
            ResultSet R = S.executeQuery(Q);
            while (R.next()) {
                int id = R.getInt("id_kamar");
                String noKamar = R.getString("no_kamar");
                String tipeKamar = R.getString("tipe_kamar");
                String hpp_kamar = R.getString("hpp");
                String harga_harian = R.getString("harga_harian");
                String deskripsi = R.getString("deskripsi");
                String link_gambar = R.getString("gambar");
                int id_sts = R.getInt("status");
                Object[] datakamar = {id, noKamar, tipeKamar, hpp_kamar, harga_harian, deskripsi, link_gambar, id_sts};
                model.addRow(datakamar);
            }

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    private void searchDataKamar() {
        try {

            String key = txtSearch.getText();
            String where = " WHERE "
                    + "id_kamar LIKE '%" + key + "%' OR "
                    + "no_kamar LIKE '%" + key + "%' OR "
                    + "tipe_kamar LIKE '%" + key + "%' OR "
                    + "hpp LIKE '%" + key + "%' OR "
                    + "harga_harian LIKE '%" + key + "%' OR "
                    + "deskripsi LIKE '%" + key + "%' OR "
                    + "status LIKE '%" + key + "%' OR "
                    + "gambar LIKE '%" + key + "%'";
            refreshDataKamar(where);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada kesalahan saat menggunakan fitur search data" + e.getMessage());
        }
    }

}
