/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import panels.ManageKamar;
import util.Kamar;
import util.Koneksi;

/**
 *
 * @author ASUS
 */
public class PreviewKamar extends javax.swing.JPanel {

    public Kamar Pdk;

    /**
     * Creates new form PreviewKamar
     */
    public PreviewKamar() {
        initComponents();
        txtNo.setText(Pdk.getNoKamar());
        txtTipe.setText(Pdk.getTipe());
        txtHarga.setText(Pdk.getHargaHarian());
        txtDesk.setText(Pdk.getDeskripsi());
        txtGambar.setText(Pdk.getGambar());
        loadImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtGambar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDesk = new javax.swing.JLabel();
        txtNo = new javax.swing.JLabel();
        txtTipe = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("N/A");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 120, 120));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setText("PREVIEW");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("desk");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 160, 50));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("no kamar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 160, 50));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("tipe");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 160, 50));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("harga");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 160, 50));

        jButton1.setText("ADD TO CART");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 220, 40));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGambar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        txtGambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGambar.setText("N/A");
        txtGambar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.add(txtGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 120, 120));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel8.setText("PREVIEW");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        txtDesk.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDesk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDesk.setText("desk");
        jPanel3.add(txtDesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 160, 50));

        txtNo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNo.setText("no kamar");
        jPanel3.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 160, 50));

        txtTipe.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTipe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTipe.setText("tipe");
        jPanel3.add(txtTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 160, 50));

        txtHarga.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHarga.setText("harga");
        jPanel3.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 160, 50));

        jButton2.setText("ADD TO CART");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 220, 40));

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtDesk;
    private javax.swing.JLabel txtGambar;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtNo;
    private javax.swing.JLabel txtTipe;
    // End of variables declaration//GEN-END:variables

//    void tampilkanData(Kamar Bk) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
    private void loadImage() {
        if (txtGambar != null) {
            try {
                URL url = new URL(txtGambar.getText());
                BufferedImage img = ImageIO.read(url);

                ImageIcon icon = new ImageIcon(img);
                txtGambar.setText(null);
                txtGambar.setIcon(null);
                txtGambar.setIcon(icon);

            } catch (IOException e) {
                System.err.println("Gagal memuat gambar dari URL (URL tidak valid atau kosong): " + e.getMessage());
            }
        }
    }
}
