/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import dialogs.NotaPembayaran;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Koneksi;
import util.Pegawai;

/**
 *
 * @author ASUS
 */
public class RiwayatTransaksi extends javax.swing.JPanel {
    
    private Pegawai Usr;

    /**
     * Creates new form RiwayatTransaksi
     */
    public RiwayatTransaksi(Pegawai user) {
        this.Usr = user;
        initComponents();
        loadData(""); // Memuat semua data awal
        cekJabatan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cariKasir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnDetailPembayaran = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelRiwayat = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setPreferredSize(new java.awt.Dimension(1610, 100));

        jLabel1.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel1.setText("Riwayat Penjualan Kamar");

        txtFilter.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Terbaru", "Terlama", "Tertinggi", "Terendah" }));
        txtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("Urutkan :");

        cariKasir.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        cariKasir.setText("Username atau ID Kasir....");
        cariKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariKasirMouseClicked(evt);
            }
        });
        cariKasir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKasirKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Kasir      :");

        btnDetailPembayaran.setBackground(new java.awt.Color(0, 204, 255));
        btnDetailPembayaran.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDetailPembayaran.setForeground(new java.awt.Color(255, 255, 255));
        btnDetailPembayaran.setText("Detail");
        btnDetailPembayaran.setEnabled(false);
        btnDetailPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailPembayaranActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariKasir, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnDetailPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(724, 724, 724))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1132, 1132, 1132))))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cariKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetailPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, -1));

        tabelRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Pembayaran", "Waktu", "Total Pembayaran", "Metode Pembayaran", "Nama Kasir", "ID Pelanggan"
            }
        ));
        tabelRiwayat.setRowHeight(40);
        tabelRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRiwayatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelRiwayat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1620, 710));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterActionPerformed
        // TODO add your handling code here:
        urutData();
    }//GEN-LAST:event_txtFilterActionPerformed

    private void tabelRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRiwayatMouseClicked
        int row = tabelRiwayat.getSelectedRow();
        if (row != -1) {
            btnDetailPembayaran.setEnabled(true);
        }
    }//GEN-LAST:event_tabelRiwayatMouseClicked

    private void cariKasirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKasirKeyReleased
        cariKasir();
        // TODO add your handling code here:
    }//GEN-LAST:event_cariKasirKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtFilter.setSelectedItem("Default");
        btnDetailPembayaran.setEnabled(false);
        if (Usr.getJabatan().equalsIgnoreCase("admin")) {
            cariKasir.setText("Username atau ID Kasir....");
        }
        
        loadData("");
        
        tabelRiwayat.clearSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cariKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariKasirMouseClicked
        cariKasir.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_cariKasirMouseClicked

    private void btnDetailPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailPembayaranActionPerformed
        int row = tabelRiwayat.getSelectedRow();
        if (row != -1) {
            // Ambil data dari kolom tabelRiwayat
            String id = tabelRiwayat.getValueAt(row, 0).toString();
            String tgl = tabelRiwayat.getValueAt(row, 1).toString();
            String total = tabelRiwayat.getValueAt(row, 2).toString();
            String metode = tabelRiwayat.getValueAt(row, 3).toString();
            String kasir = tabelRiwayat.getValueAt(row, 4).toString();
            String pelanggan = tabelRiwayat.getValueAt(row, 5).toString();

            // Panggil Dialog Nota
            NotaPembayaran nota = new NotaPembayaran(new javax.swing.JFrame(), true);
            nota.setData(id, tgl, kasir, pelanggan, total, metode);
            nota.setLocationRelativeTo(this);
            nota.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetailPembayaranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetailPembayaran;
    private javax.swing.JTextField cariKasir;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tabelRiwayat;
    private javax.swing.JComboBox<String> txtFilter;
    // End of variables declaration//GEN-END:variables

    private void cekJabatan() {
        if (Usr.getJabatan().equalsIgnoreCase("kasir")) {
            cariKasir.setText(Usr.getUsername());
            cariKasir.setEnabled(false);
        }
    }
    
    public void loadData(String additionalQuery) {
        DefaultTableModel model;
        model = (DefaultTableModel) tabelRiwayat.getModel();
        model.setRowCount(0);
        try {
            Connection conn = Koneksi.Colok();
            // Base Query: Menggabungkan tabel pembayaran dan pegawai untuk mendapatkan nama kasir
            String sql = "SELECT p.*, pg.username FROM pembayaran p "
                    + "JOIN pegawai pg ON p.id_pegawai = pg.id_pegawai WHERE 1=1 ";

            // Filter berdasarkan role
            if (Usr.getJabatan().equalsIgnoreCase("kasir")) {
                sql += " AND p.id_pegawai = '" + Usr.getId() + "' ";
            }

            // Tambahkan query tambahan (Search/Filter/Sort)
            sql += additionalQuery;
            
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_pembayaran"),
                    rs.getString("tanggal"),
                    rs.getDouble("total_harga"),
                    rs.getString("metode_pembayaran"),
                    rs.getString("username"), // Nama Kasir
                    rs.getString("id_pelanggan")
                });
            }
        } catch (SQLException e) {
            System.out.println("Error Load Data: " + e.getMessage());
        }
    }
    
    private void urutData() {
        String order = "";
        switch (txtFilter.getSelectedItem().toString()) {
            case "Terbaru":
                order = " ORDER BY tanggal DESC";
                break;
            case "Terlama":
                order = " ORDER BY tanggal ASC";
                break;
            case "Tertinggi":
                order = " ORDER BY total_harga DESC";
                break;
            case "Terendah":
                order = " ORDER BY total_harga ASC";
                break;
            default:
                order = " ORDER BY id_pembayaran DESC";
                break;
        }
        loadData(order);
    }
    
    private void cariKasir() {
        String cari = cariKasir.getText();
        // Cari berdasarkan ID atau Username kasir
        loadData(" AND (pg.username LIKE '%" + cari + "%' OR p.id_pegawai LIKE '%" + cari + "%')");
    }
}
